Fixed bug which cased a
AttributeError: 'NoneType' object has no attribute 'hasFrequencyAxis'
Traceback (most recent call last):
  File "/home/twillis/Cattery/Siamese/OMS/CompoundInterpolatedBeams.py",
line 125, in get_result

in the case when no beam patterns were found.

Also, added verbose message when missing a beam pattern.